/*
 * Author: Juan Luis Suárez Díaz
 * July, 2015
 * Music Player
 */
package GUI;

import Model.PlayingMode;
import Model.Song;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 * 
 * @author Juan Luis
 */
public class SettingsView extends javax.swing.JDialog {

    MusicPlayerView view;
    
    ArrayList<javax.swing.JTextField> rateViews;
    
    /**
     * Creates new form SettingsView
     */
    public SettingsView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        rateViews = new ArrayList();
        rateViews.add(SpinNoStars);
        rateViews.add(Spin1Star);
        rateViews.add(Spin2Stars);
        rateViews.add(Spin3Stars);
        rateViews.add(Spin4Stars);
        rateViews.add(Spin5Stars);
        rateViews.add(Spin6Stars);
        
        this.addWindowListener (new WindowAdapter() {
            @Override
            public void windowClosing (WindowEvent e) {
                ((MusicPlayerView)parent).enableSettingsButton(true);
                dispose();
            }
        });
    }

    /**
     * Sets the setting view.
     * @param mv MusicPLayerView to apply settings.
     */
    public void setView(MusicPlayerView mv){
        this.view = mv;
        
        for(int i = 0; i <= Song.getMaxRating(); i++){
            rateViews.get(i).setText(Double.toString(mv.getMusicPlayer().getRatingsFreq()[i]));    
        }
        
        ComboDefaultPlayMode.setSelectedItem(view.getMusicPlayer().getDefaultPlayMode());
        TxtDefaultPlaylist.setText(view.getMusicPlayer().getDefaultPlayList());
        repaint();
    }
    
    public double[] getRatings(){
        double[] ratings = new double[Song.getMaxRating()+1];
        for(int i = 0; i <= Song.getMaxRating(); i++){
            String val = rateViews.get(i).getText();
            try{
            ratings[i] = Double.parseDouble(val);
            }
            catch(NumberFormatException ex){
                JOptionPane.showMessageDialog(this,"Error: se esperaba un valor numérico.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        return ratings;
    }
    
    /**
     * Shows setting view.
     * @param mv MusicPlayerView to apply settings.
     */
    public void showView(MusicPlayerView mv){
        this.setView(mv);
        this.setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        BtSet = new javax.swing.JButton();
        Spin6Stars = new javax.swing.JTextField();
        Spin5Stars = new javax.swing.JTextField();
        Spin4Stars = new javax.swing.JTextField();
        Spin3Stars = new javax.swing.JTextField();
        Spin2Stars = new javax.swing.JTextField();
        Spin1Star = new javax.swing.JTextField();
        SpinNoStars = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        ComboDefaultPlayMode = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        TxtDefaultPlaylist = new javax.swing.JTextField();
        BtChoosePlaylist = new javax.swing.JButton();
        BtErase = new javax.swing.JButton();
        BtSetDefault = new javax.swing.JButton();
        BtResetDefault = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Configuración");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Media/settings_icon_xs.png")));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Frecuencias del modo de reproducción ponderada:");

        jLabel2.setText("6 estrellas:");

        jLabel3.setText("5 estrellas:");

        jLabel4.setText("4 estrellas:");

        jLabel5.setText("3 estrellas:");

        jLabel6.setText("2 estrellas:");

        jLabel7.setText("1 estrella:");

        jLabel8.setText("No valoradas:");

        BtSet.setText("Establecer configuración");
        BtSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtSetActionPerformed(evt);
            }
        });

        Spin6Stars.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Spin6Stars.setText("0");

        Spin5Stars.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Spin5Stars.setText("0");

        Spin4Stars.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Spin4Stars.setText("0");

        Spin3Stars.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Spin3Stars.setText("0");

        Spin2Stars.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Spin2Stars.setText("0");

        Spin1Star.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Spin1Star.setText("0");

        SpinNoStars.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        SpinNoStars.setText("0");

        jLabel9.setText("Modo de reproducción por defecto:");

        ComboDefaultPlayMode.setModel(new DefaultComboBoxModel<>(PlayingMode.values()));

        jLabel10.setText("Lista de reproducción inicial:");

        TxtDefaultPlaylist.setText("/home/myList.mplj");

        BtChoosePlaylist.setText("Examinar");
        BtChoosePlaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtChoosePlaylistActionPerformed(evt);
            }
        });

        BtErase.setText("Borrar");
        BtErase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtEraseActionPerformed(evt);
            }
        });

        BtSetDefault.setText("Establecer configuración por defecto");
        BtSetDefault.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtSetDefaultActionPerformed(evt);
            }
        });

        BtResetDefault.setText("Restablecer configuración de fábrica");
        BtResetDefault.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtResetDefaultActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SpinNoStars)
                                    .addComponent(Spin1Star)
                                    .addComponent(Spin2Stars)
                                    .addComponent(Spin6Stars)
                                    .addComponent(Spin5Stars)
                                    .addComponent(Spin4Stars)
                                    .addComponent(Spin3Stars)))
                            .addComponent(BtSet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxtDefaultPlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ComboDefaultPlayMode, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BtChoosePlaylist, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                                    .addComponent(BtErase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(BtSetDefault, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtResetDefault, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Spin6Stars, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Spin5Stars, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Spin4Stars, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Spin3Stars, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Spin2Stars, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Spin1Star, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(SpinNoStars, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtSet)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ComboDefaultPlayMode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BtChoosePlaylist)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtDefaultPlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtErase))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtSetDefault)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtResetDefault)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtSetActionPerformed
        try{
            view.getMusicPlayer().setRatingsFreq(getRatings());
        }
        catch(ArithmeticException ex){
            JOptionPane.showMessageDialog(this, "Error de valor: "+ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        setView(view);
    }//GEN-LAST:event_BtSetActionPerformed

    private void BtEraseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtEraseActionPerformed
        this.TxtDefaultPlaylist.setText("");
    }//GEN-LAST:event_BtEraseActionPerformed

    private void BtChoosePlaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtChoosePlaylistActionPerformed
        JFileChooser fc = new JFileChooser();
        fc.setFileFilter(new FileNameExtensionFilter("Archivos de lista de reproducción (.mplj)", "mplj"));
        int returnVal = fc.showDialog(this,"Añadir lista de reproducción");
        if(returnVal == JFileChooser.APPROVE_OPTION){
            this.TxtDefaultPlaylist.setText(fc.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_BtChoosePlaylistActionPerformed

    private void BtSetDefaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtSetDefaultActionPerformed
        view.getMusicPlayer().setDefaultSettings(getRatings(), (PlayingMode)ComboDefaultPlayMode.getSelectedItem(), 
                this.TxtDefaultPlaylist.getText());
        view.getMusicPlayer().writeDefaultSettings();
        this.setView(view);
    }//GEN-LAST:event_BtSetDefaultActionPerformed

    private void BtResetDefaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtResetDefaultActionPerformed
        view.getMusicPlayer().setInitialDefault();
        this.setView(view);
    }//GEN-LAST:event_BtResetDefaultActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtChoosePlaylist;
    private javax.swing.JButton BtErase;
    private javax.swing.JButton BtResetDefault;
    private javax.swing.JButton BtSet;
    private javax.swing.JButton BtSetDefault;
    private javax.swing.JComboBox ComboDefaultPlayMode;
    private javax.swing.JTextField Spin1Star;
    private javax.swing.JTextField Spin2Stars;
    private javax.swing.JTextField Spin3Stars;
    private javax.swing.JTextField Spin4Stars;
    private javax.swing.JTextField Spin5Stars;
    private javax.swing.JTextField Spin6Stars;
    private javax.swing.JTextField SpinNoStars;
    private javax.swing.JTextField TxtDefaultPlaylist;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
